# Generated by Django 2.2.14 on 2020-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='album_title',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_title',
        ),
        migrations.AddField(
            model_name='playlist',
            name='Playlist_name',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
