# Generated by Django 2.2.14 on 2020-07-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200714_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Playlist_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
